# Generated by Django 4.0.3 on 2022-03-11 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg'), message='File of this format cannot be loaded')]),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_webp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
