# Generated by Django 4.0.3 on 2022-03-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_media_file_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_thumbnail',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file_webp',
        ),
    ]
